dist: focal

env:
  global:
    - TWINE_NON_INTERACTIVE: true
    # TWINE_USERNAME
    - secure: KCwb9edzH8Hygls6IMv9aE0wgNxA0BSCVWAlqe6hLF220zFnr4WBUXrVriXzhsh05c0bF/XA6Bz8/4R4YyNeNwpLciTmSu4JhP9iRS8wxXOl5CnT4ZBPk2BZU2qYMuIHJehTy9hsOeia/Sq0Twk0osVUUJEnwep2Ov8eggAN6uRNBaij6PRxZWxgNqOaYCWKnTMag/tb6Vtcc834RCe+fsiR8V8HwAH3UZnZY4nwtQmbDbBmrKwYW44kn8i98zCzX8dziC7LX2dZxJK45uPzMU9eLFjYVQ4Yp8VN4acRL71WCTeymX0gDxeTLXdOXjR0LHtsE5Cb6mZNQTf09GAc2bK9z7V3ZlDzecUzTAohk400v9Jy7T8ve/5mU3u5KZNTSdx2zZaFkh4GlL6TdtNnCo2a6Wd6+XzaU4k+EM/1MG37tTM53IGpUtRtkqwGSl/dQxE//yrLW+VObNhcBlJkV6TV9FSPaTiTSDXE1gg0ZhBMZHa886swoxcIFLZRC+22Q5mYJmXsHewrg7uzxb1sat6/Qduh/zAiiaD8AbMZQjSAQb0A6JfxaUQLKNQzdcFudwWX35U3khgyolApm8in492gwqhv6Y0PMYh31BEv23W1R+VckCTsFMCVwZOkQ5tq8YSNTxbqdAbUdZ7Qp9x6sJVP7ZT2LtlEtWxJonJiGDk=
    # TWINE_PASSWORD
    - secure: knb4b+EsKnxCofAJKFwb2hwCVpYl8AXmJu74nQB7/6Mbf2sizx/p64QOuzXE5qv7iT3BGQ3gjcfdjw3v+rnY8+4HXYYgkAnRqwJiuVUHqzYqLfBVXFggoYVkScNZKQdkJy4vpWByARedxgBPC+y63fR8W/SAYF+SGVYOPrb4WB82+yGfUVYI2E7lzsCY2tNpOZlApIsufPnrfrOLcTn+rbd026RXKoSRxISNvnIxB6iqYhQtyfoKMFTkiCLY6pvRCPbGWJZ/nwotWn6FfqiuiXE8zxcAz70Th/b3pNFA0DC2YrwxWoHAaLgLTEDUSQnyZjAc92hQkcMiY8af8FfnwHzDA9QAIWqDUZl+e7wbSoh5K6KF0VAeOi9xdsf8KZgfgpq9AHJsRkByWvTT6DUg8ZaRcot+qA39ll/PifISFHaNAmb/2t1YaTQjXIe4pnMlvkihxdHsdTJ78xuocI8/5xmq1LrgrMMeRuvXH4kie8ufoBhSnyHcGkxwJkRv8gbXyphMXE79l7jmyqXc3g5snGaCJYeJJVtpd02kpDcTM1R4wGZo/fX53/hIQ3H3U1YMYcf///CGThEJD0N5LEwo4a8L6x33SiI3JbDF4/gMJujORKYbbLOg+xJr8Ok0p/JsfjlF9Qh+/Ka+QDxjMVdadFNWDhasSrDWjl5feEiUfZk=

branches:
  only:
  - master
  - "/^\\d+\\.\\d+(\\.\\d+)?((a|b|rc)?\\d+)?$/"

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
install:
  - pip install tox-travis
  - pip install codecov
script:
  - tox
after_success:
  - codecov

before_deploy:
  - pip install --upgrade build
  - pip install --upgrade twine
  - python3 -m build

deploy:
  - provider: script
    script: twine upload --repository testpypi dist/*
    on:
      repo: yeisonvargasf/yeison_todo
      branch: master
      python: 3.9
      tags: true
