dist: focal

env:
  global:
    - TWINE_NON_INTERACTIVE: true
    # TWINE_USERNAME
    - secure: b07Cr/RHRg1mR42+a+YID5sNc6DrUVyTP4ak2JLe6eHjRiuGz/f/TKTonEC1445X7uAvhg5GsNYHFu34VuyM8Jw2jhoDxSMLfZaNHI/zGbRif7q5D+yadyxLnzaDOBJT27hxds3Yip+jgH+DokAj5YBHdZed9c5SfWNSvtLYj+GHstIiElrpLCbX4aVbmwn90ZY/T8PLzVTfgHH9t0M5assKhyXP2YCNifXdI7mHLfqxRxqD7uU/v3cPb+vDFg0LerVOgGcENQ9GX2LkCbfP6od+3WPhDO+RihUk30Vaus6xdggHoj0cLDRgB8ARViTZNKcbN3nPbUe35aOqBbEH1qOgyz2vQQ8a0LP7M3f3lpjvMDFw1w0GXYFwWDW9Kj5SXYZJsGEIKfncGY2sd632FTjJrU9ICHoS0K2ki6kp6BZUjeFmqjKVMpOvKAGtqaz80onKNEUB0dAfhGA+TYKBFAYcElz+8iVw4XTrGdQTP5DCT1a2fLUXQTF/8nhjWBk573PoFXVaIyTSYYWn4IqqnAYA0vVpmyQuW0NS74U+rE7YWpTdw76T1c4z2hvLYLpqTsUE8WJEhlQ729ESSdmfwHLBUgDeQyW6+X2LbiDyy+IuAhaYC1FRuqSNQZDFtTZ2wstnPO3vSJWjmuu2bLQxJMSkOqBdbUNhvpdLv13xnGg=
    # TWINE_PASSWORD
    - secure: V4MirHc8pXAqTCUCpzH6gPCuyjqAd+1B7iNkSRAQiS6DmwF3nyfRwGoa7wD6E9HpDW49/4yfTYYlcJjDy+8PJVdirj9/KB8ZaOnuUgtib05FJ6RGFA5WQtUG4oQAh0Rc05JKsc4+hHOPN3c/zDmLmizp2XyZmltFsxbu1a+5T7wFCpqxpUbMqf+6GerJQGJs96RBBHRcFqgzCXG2CGVKR8F+l0FQiDVdKE2QsGPDu4cZxlCT1icn5EESpbG0PvcN4tC3geawfcIU+IhoH49RC+qg3caJNlirdomdBes5ePOnSzA2A4GjIckuTP45o6jLYfKGvns3mQpgFt6YfBIDZeoYXDVQtW8juoS+QdiDk3Bh5atyszzs/WKiKYYIA/SFI11HEejUdlGDI17WufKWEjD+aTUWPpi4Fs1oFFhf2SS6Ghc9lBBSeGinPkAj2nEA5GWzkvtXyXC4lI6VnQegNgUiZiWYmpZR9GaK7Pqv+JnuyyS6ddWMBAyEyvsQNzavT6N2xLLzgXExH1QqllnCwGx91PwoaLJWbzsHP1g8nkLjLfqxqpvKqTKq6QexzJmNLqxgSJSTKv0f8mhejydIu/9hSbIlddG5+VD68odMN2mBUBhiZFTJYHqr6TEezURPw1Y/hAAiFY7LesN1w0zi4dznKR6n2IG4rLVwXKWlzeM=

branches:
  only:
  - master
  - /^\d+\.\d+(\.\d+)?((a|b|rc)?\d+)?$/

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
install:
  - pip install tox-travis
  - pip install codecov
script:
  - tox
after_success:
  - codecov

before_deploy:
  - pip install --upgrade build
  - pip install --upgrade twine

deploy:
  - provider: script
    script: python3 -m build && twine upload --repository testpypi dist/*
    on:
      repo: yeisonvargasf/yeison_todo
      branch: master
      python: 3.9
      tags: true
