version: 0.1b1+{build}
image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
branches:
  only:
    - master
    - appveyor-fixes
    - /^\d+\.\d+(\.\d+)?((a|b|rc)?\d+)?$/

# note: on macOS the binary is built using Python 3.7 (installed via Homebrew), because
# the shipped Python lacks libraries PyInstaller needs.
stack: python 3.6

# note: 32 bit linux binary is build using docker
for:
-
  matrix:
    only:
      - image: Ubuntu

  services:
    - docker

environment:
  PY_DIR: C:\Python36-x64

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

build: off

artifacts:
  - path: "dist\\yeison_todo-win-i686.exe"
    name: "yeison_todo-win-i686.exe"
  - path: "dist\\yeison_todo-win-x86_64.exe"
    name: "yeison_todo-win-x86_64.exe"
  - path: "dist\\yeison_todo-linux-i686"
    name: "yeison_todo-linux-i686"
  - path: "dist\\yeison_todo-linux-x86_64"
    name: "yeison_todo-linux-x86_64"
  - path: "dist\\yeison_todo-macos-x86_64"
    name: "yeison_todo-macos-x86_64"

install:
  - "python --version"
  - "python appveyor.py install"

test_script:
  - "python appveyor.py test"
  - "python appveyor.py dist"


deploy:
  - provider: GitHub
    description: 'yeison_todo Binary Release'
    auth_token:
      secure: 85QEE4bIxh+Z0f3TwM9GiyY1ntr/04eGX9V7+1Yjsk77M6sk1/9meSPEvhnvSzZD
    on:
      APPVEYOR_REPO_TAG: true
